import React, { useState } from 'react';

const faqs = [
  {
    question: "How does the AI generate travel plans?",
    answer: "Our AI analyzes your preferences, travel dates, budget, and real-time data to craft a personalized itinerary that matches your unique style."
  },
  {
    question: "Can I customize my itinerary?",
    answer: "Absolutely! The AI provides a baseline itinerary which you can easily tweak, swap activities, or adjust timings to perfectly suit your needs."
  },
  {
    question: "Is the platform free?",
    answer: "We offer a robust free tier for basic travel planning. Premium features, like collaborative planning and advanced AI recommendations, are available through a subscription."
  },
  {
    question: "Does it support international trips?",
    answer: "Yes, our platform supports both domestic and international travel planning, covering destinations across the globe."
  },
  {
    question: "Can I plan solo and family trips?",
    answer: "Definitely. You can specify the number of travelers and relationship types (solo, couple, family, friends) and the AI will tailor the activities accordingly."
  },
  {
    question: "How are recommendations generated?",
    answer: "Recommendations are generated by cross-referencing thousands of verified reviews, location data, and your personal interests using our advanced machine learning models."
  },
  {
    question: "Can I save trips?",
    answer: "Yes, you can save as many trips as you want to your account and access them from any device at any time."
  },
  {
    question: "Is real-time weather included?",
    answer: "Yes, our itineraries take historical and forecasted weather patterns into account to ensure your outdoor activities are perfectly timed."
  },
  {
    question: "Does the platform suggest hotels and restaurants?",
    answer: "Yes! We provide tailored recommendations for accommodations and dining based on your budget and culinary preferences."
  }
];

const FAQItem = ({ question, answer }) => {
  const [isOpen, setIsOpen] = useState(false);

  return (
    <div className="border-b border-gray-200 py-4">
      <button 
        onClick={() => setIsOpen(!isOpen)} 
        className="flex justify-between items-center w-full text-left focus:outline-none"
      >
        <h3 className="text-lg font-medium text-slate-800">{question}</h3>
        <span className="ml-6 flex-shrink-0">
          <svg 
            className={`h-6 w-6 transform ${isOpen ? 'rotate-180' : ''} transition-transform duration-200 text-blue-500`} 
            fill="none" 
            viewBox="0 0 24 24" 
            stroke="currentColor"
          >
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 9l-7 7-7-7" />
          </svg>
        </span>
      </button>
      <div 
        className={`mt-2 pr-12 text-gray-600 transition-all duration-300 ease-in-out overflow-hidden ${isOpen ? 'max-h-96 opacity-100' : 'max-h-0 opacity-0'}`}
      >
        <p className="py-2">{answer}</p>
      </div>
    </div>
  );
};

const FaqPage = () => {
  return (
    <div className="max-w-4xl mx-auto px-4 py-16 sm:px-6 lg:px-8">
      <div className="text-center mb-12">
        <h1 className="text-4xl font-extrabold text-slate-900 tracking-tight sm:text-5xl">Frequently Asked Questions</h1>
        <p className="mt-4 text-xl text-gray-500">
          Everything you need to know about planning your next adventure with our AI.
        </p>
      </div>

      <div className="bg-white rounded-2xl shadow-sm border border-gray-100 p-6 md:p-8">
        <div className="divide-y divide-gray-200">
          {faqs.map((faq, index) => (
            <FAQItem key={index} question={faq.question} answer={faq.answer} />
          ))}
        </div>
      </div>
    </div>
  );
};

export default FaqPage;
