import { Link } from 'react-router-dom';
import { useState } from 'react';
import Button from '../components/common/Button';

export default function LandingPage() {
  const [storyIndex, setStoryIndex] = useState(0);

  const uniqueExperiences = [
    {
      slug: 'safari',
      title: 'Safari in Africa',
      desc: "Embark on a thrilling safari to witness majestic wildlife in Africa's vast savannas.",
      img: 'https://images.unsplash.com/photo-1516426122078-c23e76319801?w=800',
    },
    {
      slug: 'skydiving',
      title: 'Skydiving in Dubai',
      desc: "Experience an adrenaline rush skydiving over Dubai's iconic Palm Jumeirah.",
      img: 'https://images.unsplash.com/photo-1530143584546-02191bc84eb5?w=800',
    },
    {
      slug: 'northernlights',
      title: 'Northern Lights in Europe',
      desc: "Chase the mesmerizing Northern Lights in Europe's Arctic regions.",
      img: 'https://images.unsplash.com/photo-1531366936337-7c912a4589a7?w=800',
    },
  ];

  const continents = [
    {
      slug: 'northamerica',
      name: 'North America',
      desc: 'A diverse continent known for its stunning economic powerhouses.',
      img: 'https://images.unsplash.com/photo-1477959858617-67f85cf4f1df?w=800',
    },
    {
      slug: 'southamerica',
      name: 'South America',
      desc: 'A vibrant continent known for its diverse cultures and breathtaking landscapes.',
      img: 'https://images.unsplash.com/photo-1483729558449-99ef09a8c325?w=800',
    },
    {
      slug: 'europe',
      name: 'Europe',
      desc: 'A diverse continent rich in history, culture, and natural beauty.',
      img: 'https://images.unsplash.com/photo-1467269204594-9661b134dd2b?w=800',
    },
  ];

  const features = [
    { icon: '🤖', title: 'AI-Powered Planning', desc: 'Smart itineraries generated by artificial intelligence, tailored to your travel style and preferences.' },
    { icon: '💰', title: 'Budget Intelligence', desc: 'ML-powered cost predictions and real-time expense tracking to keep your trip on budget.' },
    { icon: '🗺️', title: 'Interactive Maps', desc: 'Visualize your journey with interactive maps, route optimization, and points of interest.' },
    { icon: '💬', title: 'AI Travel Assistant', desc: 'Get instant answers about visas, packing, local customs, and destination tips.' },
    { icon: '📊', title: 'Smart Recommendations', desc: 'Semantic search and personalized destination recommendations using machine learning.' },
    { icon: '👥', title: 'Collaborative Trips', desc: 'Plan together with friends and family with shared itineraries and real-time editing.' },
  ];

  const testimonials = [
    { name: 'Priya Sharma', location: 'Mumbai', text: 'WanderIQ helped me plan a 10-day Rajasthan trip in under 30 minutes. The budget predictor was surprisingly accurate!', avatar: '👩‍💼' },
    { name: 'Arjun Nair', location: 'Bangalore', text: 'The AI itinerary for our Bali honeymoon was perfect. Every restaurant and activity recommendation was spot on.', avatar: '👨‍💻' },
    { name: 'Sneha Patel', location: 'Delhi', text: 'I love how the chatbot knows visa requirements and packing tips. It\'s like having a travel agent in your pocket!', avatar: '👩‍🎨' },
  ];

  const destinations = [
    { name: 'Goa', tag: 'Beach Paradise', img: 'https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?w=600' },
    { name: 'Ladakh', tag: 'Mountain Adventure', img: 'https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?w=600' },
    { name: 'Bali', tag: 'Tropical Escape', img: 'https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=600' },
    { name: 'Paris', tag: 'Cultural Icon', img: 'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=600' },
  ];

  const travelStories = [
    {
      title: 'Tokyo Cityscape',
      description: 'Tokyo is famous for its unique blend of traditional culture and modern innovation. It\'s a city known for its vibrant nightlife and iconic landmarks.',
      image: 'https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=600',
      link: 'https://www.instagram.com/p/DGkXd-_s0UC/',
    },
    {
      title: 'Snorkeling in Maldives',
      description: 'Snorkeling in the Maldives offers a vibrant underwater experience with abundant marine life and stunning coral reefs. The warm water temperatures and calm, accessible sites make it perfect for all skill levels.',
      image: 'https://images.unsplash.com/photo-1514282401047-d79a71a590e8?w=600',
      link: 'https://www.instagram.com/aaysharma/p/DB0VbR0SKdN/?img_index=1',
    },
    {
      title: 'Hiking in Alps',
      description: 'Hiking in the Alps offers a diverse range of experiences, from short day hikes to multi-day treks, all within a stunning mountain setting. The best time to hike is generally from mid-June to late September.',
      image: 'https://images.unsplash.com/photo-1530122037265-a5f1f91d3b99?w=600',
      link: 'https://www.instagram.com/exploringnewzealand/?hl=en',
    },
    {
      title: 'Santorini Sunset',
      description: 'Santorini\'s sunset became famous through a combination of its natural beauty, social media exposure, and strategic tourism promotion efforts.',
      image: 'https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?w=600',
      link: 'https://www.instagram.com/topspotsthailand/?hl=en',
    },
  ];

  const prevStory = () => setStoryIndex((i) => (i === 0 ? travelStories.length - 1 : i - 1));
  const nextStory = () => setStoryIndex((i) => (i === travelStories.length - 1 ? 0 : i + 1));
  const story = travelStories[storyIndex];

  return (
    <div className="min-h-screen">
      {/* Hero */}
      <section className="relative h-[90vh] min-h-[600px] flex items-center overflow-hidden">
        <div className="absolute inset-0">
          <video 
            src="/download.mp4" 
            autoPlay 
            loop 
            muted 
            playsInline 
            className="w-full h-full object-cover"
          />
          <div className="absolute inset-0 bg-gradient-to-r from-black/70 via-black/40 to-transparent" />
        </div>
        <div className="relative max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 text-white">
          <div className="max-w-2xl animate-slide-up">
            <p className="text-primary-light font-semibold text-sm uppercase tracking-widest mb-4">AI-Powered Travel Planning</p>
            <h1 className="font-display text-5xl sm:text-6xl lg:text-7xl font-bold leading-tight mb-6">
              Plan Smarter.<br /><span className="text-coral">Travel Better.</span>
            </h1>
            <p className="text-white/80 text-lg sm:text-xl leading-relaxed mb-8 max-w-lg">
              Discover destinations, build smart itineraries, and manage budgets with the power of artificial intelligence.
            </p>
            <div className="flex flex-wrap gap-4">
              <Link to="/signup"><Button className="text-lg px-8 py-4">Start Planning Free →</Button></Link>
              <Link to="/discover"><Button variant="ghost" className="text-lg px-8 py-4 border-white text-white hover:bg-white hover:text-primary">Explore Destinations</Button></Link>
            </div>
          </div>
        </div>

        {/* Scroll indicator */}
        <div className="absolute bottom-8 left-1/2 -translate-x-1/2 animate-float">
          <div className="w-6 h-10 rounded-full border-2 border-white/50 flex items-start justify-center p-1">
            <div className="w-1.5 h-3 bg-white/80 rounded-full animate-bounce" />
          </div>
        </div>
      </section>

      {/* Trending Destinations */}
      <section className="section-padding bg-sand">
        <div className="max-w-7xl mx-auto">
          <div className="text-center mb-12">
            <p className="text-primary font-semibold text-sm uppercase tracking-widest mb-2">Popular Picks</p>
            <h2 className="font-display text-4xl font-bold text-body">Trending Destinations</h2>
          </div>
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6">
            {destinations.map((d) => (
              <Link key={d.name} to="/discover" className="card group cursor-pointer">
                <div className="relative h-64 overflow-hidden">
                  <img src={d.img} alt={d.name} className="w-full h-full object-cover transition-transform duration-700 group-hover:scale-110" loading="lazy" />
                  <div className="absolute inset-0 bg-gradient-to-t from-black/60 to-transparent" />
                  <div className="absolute bottom-4 left-4">
                    <p className="text-white/70 text-xs font-semibold uppercase tracking-wider">{d.tag}</p>
                    <h3 className="text-white font-display text-2xl font-bold">{d.name}</h3>
                  </div>
                </div>
              </Link>
            ))}
          </div>
        </div>
      </section>

      {/* Unique Travel Experiences */}
      <section className="section-padding bg-white">
        <div className="max-w-7xl mx-auto">
          <div className="text-center mb-12">
            <p className="text-primary font-semibold text-sm uppercase tracking-widest mb-2">Bucket List</p>
            <h2 className="font-display text-4xl font-bold text-body">Unique Travel Experiences</h2>
            <div className="mt-4 mx-auto w-24 h-[3px] rounded-full bg-gradient-to-r from-primary to-coral" />
          </div>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-7">
            {uniqueExperiences.map((exp) => (
              <div key={exp.slug} className="group relative rounded-card overflow-hidden shadow-card cursor-pointer">
                <div className="relative h-72 overflow-hidden">
                  <img
                    src={exp.img}
                    alt={exp.title}
                    className="w-full h-full object-cover transition-transform duration-700 group-hover:scale-110"
                  />
                  <div className="absolute inset-0 bg-gradient-to-t from-black/75 via-black/20 to-transparent" />
                  <div className="absolute bottom-0 left-0 right-0 p-5">
                    <h3 className="text-white font-display text-2xl font-bold mb-1">{exp.title}</h3>
                    <p className="text-white/80 text-sm leading-relaxed mb-4">{exp.desc}</p>
                    <Link
                      to={`/experiences/${exp.slug}`}
                      className="inline-block bg-white text-body font-semibold text-sm px-5 py-2 rounded-full hover:bg-primary hover:text-white transition-all duration-300"
                    >
                      Explore Now
                    </Link>
                  </div>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Select Your Desired Continent */}
      <section className="section-padding bg-sand">
        <div className="max-w-7xl mx-auto">
          <div className="text-center mb-12">
            <p className="text-primary font-semibold text-sm uppercase tracking-widest mb-2">Where to Next?</p>
            <h2 className="font-display text-4xl font-bold text-body">Select Your Desired Continent</h2>
            <div className="mt-4 mx-auto w-24 h-[3px] rounded-full bg-gradient-to-r from-primary to-coral" />
          </div>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-7">
            {continents.map((c) => (
              <div key={c.slug} className="group card cursor-pointer">
                <div className="relative h-60 overflow-hidden">
                  <img
                    src={c.img}
                    alt={c.name}
                    className="w-full h-full object-cover transition-transform duration-700 group-hover:scale-110"
                  />
                  <div className="absolute inset-0 bg-gradient-to-t from-black/60 to-transparent" />
                  <div className="absolute bottom-4 left-4 right-4">
                    <h3 className="text-white font-display text-2xl font-bold">{c.name}</h3>
                  </div>
                </div>
                <div className="p-5">
                  <p className="text-muted text-sm leading-relaxed mb-4">{c.desc}</p>
                  <Link
                    to={`/continents/${c.slug}`}
                    className="inline-block text-sm font-bold text-primary border border-primary px-5 py-2 rounded-full hover:bg-primary hover:text-white transition-all duration-300"
                  >
                    Explore More +
                  </Link>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Features */}
      <section className="section-padding bg-white">
        <div className="max-w-7xl mx-auto">
          <div className="text-center mb-16">
            <p className="text-primary font-semibold text-sm uppercase tracking-widest mb-2">Why WanderIQ</p>
            <h2 className="font-display text-4xl font-bold text-body mb-4">Everything You Need to Plan</h2>
            <p className="text-muted max-w-2xl mx-auto">From AI-powered recommendations to interactive maps and budget tracking, WanderIQ is your complete travel planning companion.</p>
          </div>
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
            {features.map((f, i) => (
              <div key={i} className="p-8 rounded-card border border-border hover:shadow-card hover:border-primary/20 transition-all duration-300 group">
                <div className="text-4xl mb-4 group-hover:scale-110 transition-transform">{f.icon}</div>
                <h3 className="font-display text-xl font-semibold mb-2 text-body">{f.title}</h3>
                <p className="text-muted text-sm leading-relaxed">{f.desc}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Travel Stories */}
      <section className="section-padding bg-sand-light">
        <div className="max-w-4xl mx-auto">
          <div className="text-center mb-10">
            <h2 className="font-display text-4xl font-bold text-body">Travel Stories</h2>
            <div className="mt-3 mx-auto w-48 h-[3px] bg-gradient-to-r from-transparent via-primary to-transparent" />
          </div>

          <div className="bg-white rounded-card shadow-card p-6 sm:p-8 relative">
            <div className="flex flex-col md:flex-row gap-6 items-center">
              {/* Story Image */}
              <div className="w-full md:w-[45%] flex-shrink-0 rounded-card overflow-hidden shadow-sm">
                <img
                  src={story.image}
                  alt={story.title}
                  className="w-full h-56 sm:h-64 object-cover transition-transform duration-500 hover:scale-105"
                />
              </div>

              {/* Story Content */}
              <div className="flex-1 space-y-4">
                <h3 className="font-display text-2xl font-bold text-body">{story.title}</h3>
                <div className="flex gap-3">
                  <div className="w-1 bg-primary rounded-full flex-shrink-0" />
                  <p className="text-muted text-sm leading-relaxed italic">"{story.description}"</p>
                </div>
                <a
                  href={story.link}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="inline-block bg-primary hover:bg-primary-light text-white font-semibold text-sm px-6 py-2.5 rounded-input transition-all duration-300 hover:shadow-glow"
                >
                  Read More
                </a>
              </div>
            </div>

            {/* Carousel Arrows */}
            <button
              onClick={prevStory}
              className="absolute left-2 top-1/2 -translate-y-1/2 w-10 h-10 bg-white/90 hover:bg-white border border-border rounded-full shadow-card flex items-center justify-center text-muted hover:text-primary transition-all"
              aria-label="Previous story"
            >
              <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 19l-7-7 7-7" /></svg>
            </button>
            <button
              onClick={nextStory}
              className="absolute right-2 top-1/2 -translate-y-1/2 w-10 h-10 bg-white/90 hover:bg-white border border-border rounded-full shadow-card flex items-center justify-center text-muted hover:text-primary transition-all"
              aria-label="Next story"
            >
              <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 5l7 7-7 7" /></svg>
            </button>

            {/* Dots */}
            <div className="flex justify-center gap-2 mt-6">
              {travelStories.map((_, i) => (
                <button
                  key={i}
                  onClick={() => setStoryIndex(i)}
                  className={`h-2 rounded-full transition-all duration-300 ${i === storyIndex ? 'bg-primary w-8' : 'bg-border w-4 hover:bg-primary/40'}`}
                  aria-label={`Go to story ${i + 1}`}
                />
              ))}
            </div>
          </div>
        </div>
      </section>

      {/* ── Blogs Preview ───────────────────────────────────── */}
      <section className="section-padding bg-white">
        <div className="max-w-7xl mx-auto">
          <div className="text-center mb-12">
            <p className="text-primary font-semibold text-sm uppercase tracking-widest mb-2">📝 From Our Writers</p>
            <h2 className="font-display text-4xl font-bold text-body">Travel Stories & Insights</h2>
            <p className="text-muted mt-3 max-w-xl mx-auto text-sm">
              Expert tips, hidden destinations, AI travel hacks, and real experiences — curated for the modern traveler.
            </p>
            <div className="mt-4 mx-auto w-24 h-[3px] rounded-full bg-gradient-to-r from-primary to-coral" />
          </div>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-7">
            {[
              {
                slug: 'hidden-gems-southeast-asia',
                category: 'Destinations',
                color: '#0F6E56',
                title: 'Hidden Gems of Southeast Asia You Must Visit',
                desc: 'Beyond Bali and Bangkok lies a world of undiscovered wonders — misty limestone karsts and ancient temples.',
                img: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=600',
                time: '7 min read',
              },
              {
                slug: 'ai-travel-planning-revolution',
                category: 'Technology',
                color: '#7C3AED',
                title: 'How AI Is Revolutionizing the Way We Plan Trips',
                desc: 'Forget spreadsheets. AI-powered itinerary builders are changing travel planning forever.',
                img: 'https://images.unsplash.com/photo-1677442135703-1787eea5ce01?w=600',
                time: '6 min read',
              },
              {
                slug: 'budget-europe-backpacking',
                category: 'Tips & Tricks',
                color: '#C85D38',
                title: 'Backpacking Europe on ₹1,500 a Day: The 2025 Guide',
                desc: 'From Lisbon to Ljubljana, savvy travelers prove Europe does not have to drain your bank account.',
                img: 'https://images.unsplash.com/photo-1467269204594-9661b134dd2b?w=600',
                time: '10 min read',
              },
            ].map((b) => (
              <Link key={b.slug} to={`/blogs/${b.slug}`} className="card group cursor-pointer" style={{ textDecoration: 'none' }}>
                <div className="relative h-52 overflow-hidden">
                  <img src={b.img} alt={b.title} className="w-full h-full object-cover transition-transform duration-700 group-hover:scale-110" loading="lazy" />
                  <div className="absolute inset-0 bg-gradient-to-t from-black/60 to-transparent" />
                  <span
                    className="absolute top-3 left-3 text-white text-xs font-bold px-3 py-1 rounded-full"
                    style={{ background: b.color, letterSpacing: '0.5px', textTransform: 'uppercase', fontSize: '10px' }}
                  >
                    {b.category}
                  </span>
                  <span className="absolute bottom-3 right-3 bg-black/60 text-white text-xs px-2 py-1 rounded-full backdrop-blur-sm">
                    ⏱ {b.time}
                  </span>
                </div>
                <div className="p-5">
                  <h3 className="font-display text-lg font-bold text-body mb-2 leading-snug">{b.title}</h3>
                  <p className="text-muted text-sm leading-relaxed mb-4">{b.desc}</p>
                  <span className="text-sm font-bold text-primary inline-flex items-center gap-1 group-hover:gap-2 transition-all">
                    Read Article <span>→</span>
                  </span>
                </div>
              </Link>
            ))}
          </div>

          <div className="text-center mt-10">
            <Link
              to="/blogs"
              className="inline-flex items-center gap-2 bg-primary text-white font-semibold px-8 py-3 rounded-input hover:bg-primary-light transition-all duration-300 hover:shadow-glow"
            >
              📚 Explore All Articles
            </Link>
          </div>
        </div>
      </section>

      {/* Experience the Journey */}
      <section className="section-padding bg-white">

        <div className="max-w-4xl mx-auto">
          <div className="text-center mb-10">
            <h2 className="font-display text-4xl font-bold text-body italic">Experience the Journey</h2>
            <div className="mt-3 mx-auto w-48 h-[3px] bg-gradient-to-r from-transparent via-primary to-transparent" />
          </div>

          <div className="bg-sand-light rounded-card shadow-card overflow-hidden">
            <div className="relative w-full" style={{ paddingBottom: '56.25%' }}>
              <iframe
                className="absolute inset-0 w-full h-full"
                src="https://www.youtube.com/embed/ChOhcHVqcIY"
                title="TOP 50 • Most Beautiful Places in the World 8K ULTRA HD"
                frameBorder="0"
                allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"
                allowFullScreen
              />
            </div>
            <div className="p-6 text-center">
              <p className="text-muted text-sm">From tropical beaches to snowy peaks, WanderIQ takes you there.</p>
            </div>
          </div>
        </div>
      </section>

      {/* Testimonials */}
      <section className="section-padding bg-sand">
        <div className="max-w-7xl mx-auto">
          <div className="text-center mb-12">
            <p className="text-primary font-semibold text-sm uppercase tracking-widest mb-2">Happy Travelers</p>
            <h2 className="font-display text-4xl font-bold text-body">What Our Users Say</h2>
          </div>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
            {testimonials.map((t, i) => (
              <div key={i} className="bg-white p-8 rounded-card shadow-card">
                <p className="text-body text-sm leading-relaxed mb-6 italic">"{t.text}"</p>
                <div className="flex items-center gap-3">
                  <div className="w-10 h-10 bg-primary/10 rounded-full flex items-center justify-center text-xl">{t.avatar}</div>
                  <div>
                    <p className="font-semibold text-sm text-body">{t.name}</p>
                    <p className="text-xs text-muted">{t.location}</p>
                  </div>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* CTA */}
      <section className="section-padding bg-primary text-white text-center">
        <div className="max-w-3xl mx-auto">
          <h2 className="font-display text-4xl font-bold mb-4">Ready for Your Next Adventure?</h2>
          <p className="text-white/80 text-lg mb-8">Join thousands of smart travelers. Start planning your dream trip today.</p>
          <Link to="/signup"><Button className="text-lg px-10 py-4">Get Started Free →</Button></Link>
        </div>
      </section>
    </div>
  );
}
