import { Link } from 'react-router-dom';
import Button from '../components/common/Button';

export default function LandingPage() {
  const features = [
    { icon: '🤖', title: 'AI-Powered Planning', desc: 'Smart itineraries generated by artificial intelligence, tailored to your travel style and preferences.' },
    { icon: '💰', title: 'Budget Intelligence', desc: 'ML-powered cost predictions and real-time expense tracking to keep your trip on budget.' },
    { icon: '🗺️', title: 'Interactive Maps', desc: 'Visualize your journey with interactive maps, route optimization, and points of interest.' },
    { icon: '💬', title: 'AI Travel Assistant', desc: 'Get instant answers about visas, packing, local customs, and destination tips.' },
    { icon: '📊', title: 'Smart Recommendations', desc: 'Semantic search and personalized destination recommendations using machine learning.' },
    { icon: '👥', title: 'Collaborative Trips', desc: 'Plan together with friends and family with shared itineraries and real-time editing.' },
  ];

  const testimonials = [
    { name: 'Priya Sharma', location: 'Mumbai', text: 'WanderIQ helped me plan a 10-day Rajasthan trip in under 30 minutes. The budget predictor was surprisingly accurate!', avatar: '👩‍💼' },
    { name: 'Arjun Nair', location: 'Bangalore', text: 'The AI itinerary for our Bali honeymoon was perfect. Every restaurant and activity recommendation was spot on.', avatar: '👨‍💻' },
    { name: 'Sneha Patel', location: 'Delhi', text: 'I love how the chatbot knows visa requirements and packing tips. It\'s like having a travel agent in your pocket!', avatar: '👩‍🎨' },
  ];

  const destinations = [
    { name: 'Goa', tag: 'Beach Paradise', img: 'https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?w=600' },
    { name: 'Ladakh', tag: 'Mountain Adventure', img: 'https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?w=600' },
    { name: 'Bali', tag: 'Tropical Escape', img: 'https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=600' },
    { name: 'Paris', tag: 'Cultural Icon', img: 'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=600' },
  ];

  return (
    <div className="min-h-screen">
      {/* Hero */}
      <section className="relative h-[90vh] min-h-[600px] flex items-center overflow-hidden">
        <div className="absolute inset-0">
          <img src="https://images.unsplash.com/photo-1488646953014-85cb44e25828?w=1920" alt="Travel" className="w-full h-full object-cover" />
          <div className="absolute inset-0 bg-gradient-to-r from-black/70 via-black/40 to-transparent" />
        </div>
        <div className="relative max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 text-white">
          <div className="max-w-2xl animate-slide-up">
            <p className="text-primary-light font-semibold text-sm uppercase tracking-widest mb-4">AI-Powered Travel Planning</p>
            <h1 className="font-display text-5xl sm:text-6xl lg:text-7xl font-bold leading-tight mb-6">
              Plan Smarter.<br /><span className="text-coral">Travel Better.</span>
            </h1>
            <p className="text-white/80 text-lg sm:text-xl leading-relaxed mb-8 max-w-lg">
              Discover destinations, build smart itineraries, and manage budgets with the power of artificial intelligence.
            </p>
            <div className="flex flex-wrap gap-4">
              <Link to="/signup"><Button className="text-lg px-8 py-4">Start Planning Free →</Button></Link>
              <Link to="/discover"><Button variant="ghost" className="text-lg px-8 py-4 border-white text-white hover:bg-white hover:text-primary">Explore Destinations</Button></Link>
            </div>
          </div>
        </div>

        {/* Scroll indicator */}
        <div className="absolute bottom-8 left-1/2 -translate-x-1/2 animate-float">
          <div className="w-6 h-10 rounded-full border-2 border-white/50 flex items-start justify-center p-1">
            <div className="w-1.5 h-3 bg-white/80 rounded-full animate-bounce" />
          </div>
        </div>
      </section>

      {/* Trending Destinations */}
      <section className="section-padding bg-sand">
        <div className="max-w-7xl mx-auto">
          <div className="text-center mb-12">
            <p className="text-primary font-semibold text-sm uppercase tracking-widest mb-2">Popular Picks</p>
            <h2 className="font-display text-4xl font-bold text-body">Trending Destinations</h2>
          </div>
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6">
            {destinations.map((d) => (
              <Link key={d.name} to="/discover" className="card group cursor-pointer">
                <div className="relative h-64 overflow-hidden">
                  <img src={d.img} alt={d.name} className="w-full h-full object-cover transition-transform duration-700 group-hover:scale-110" loading="lazy" />
                  <div className="absolute inset-0 bg-gradient-to-t from-black/60 to-transparent" />
                  <div className="absolute bottom-4 left-4">
                    <p className="text-white/70 text-xs font-semibold uppercase tracking-wider">{d.tag}</p>
                    <h3 className="text-white font-display text-2xl font-bold">{d.name}</h3>
                  </div>
                </div>
              </Link>
            ))}
          </div>
        </div>
      </section>

      {/* Features */}
      <section className="section-padding bg-white">
        <div className="max-w-7xl mx-auto">
          <div className="text-center mb-16">
            <p className="text-primary font-semibold text-sm uppercase tracking-widest mb-2">Why WanderIQ</p>
            <h2 className="font-display text-4xl font-bold text-body mb-4">Everything You Need to Plan</h2>
            <p className="text-muted max-w-2xl mx-auto">From AI-powered recommendations to interactive maps and budget tracking, WanderIQ is your complete travel planning companion.</p>
          </div>
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
            {features.map((f, i) => (
              <div key={i} className="p-8 rounded-card border border-border hover:shadow-card hover:border-primary/20 transition-all duration-300 group">
                <div className="text-4xl mb-4 group-hover:scale-110 transition-transform">{f.icon}</div>
                <h3 className="font-display text-xl font-semibold mb-2 text-body">{f.title}</h3>
                <p className="text-muted text-sm leading-relaxed">{f.desc}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Testimonials */}
      <section className="section-padding bg-sand">
        <div className="max-w-7xl mx-auto">
          <div className="text-center mb-12">
            <p className="text-primary font-semibold text-sm uppercase tracking-widest mb-2">Happy Travelers</p>
            <h2 className="font-display text-4xl font-bold text-body">What Our Users Say</h2>
          </div>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
            {testimonials.map((t, i) => (
              <div key={i} className="bg-white p-8 rounded-card shadow-card">
                <p className="text-body text-sm leading-relaxed mb-6 italic">"{t.text}"</p>
                <div className="flex items-center gap-3">
                  <div className="w-10 h-10 bg-primary/10 rounded-full flex items-center justify-center text-xl">{t.avatar}</div>
                  <div>
                    <p className="font-semibold text-sm text-body">{t.name}</p>
                    <p className="text-xs text-muted">{t.location}</p>
                  </div>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* CTA */}
      <section className="section-padding bg-primary text-white text-center">
        <div className="max-w-3xl mx-auto">
          <h2 className="font-display text-4xl font-bold mb-4">Ready for Your Next Adventure?</h2>
          <p className="text-white/80 text-lg mb-8">Join thousands of smart travelers. Start planning your dream trip today.</p>
          <Link to="/signup"><Button className="text-lg px-10 py-4">Get Started Free →</Button></Link>
        </div>
      </section>
    </div>
  );
}
